### ISSUE TITLE
?????????????????????

### ISSUE THREAD

**Issue by cameronjroe** [isaacs/rimraf#103]
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: rimraf: missing options

**Comment by yoshuawuyts** [comment]
This issue is not particularly helpful, could you please explain what is happening, which versions of things you're running and ideally provide a repro? The more details you provide, the bigger the chance is that someone takes their time to help you. Cheers!

**Comment by cameronjroe** [comment]
Having a rough day.
