### ISSUE TITLE
CLI exclude

### ISSUE THREAD

**Issue by iyel** [isaacs/rimraf#104]
Hello!
Cand I exclude files when rimrafing folder from CLI?

**Comment by isaacs** [comment]
No.  The intent of the cli is to exactly mimic `rm -rf`, which does not allow exclusions.

Use an argument that doesn't include the thing you want to not remove.

**Comment by sindresorhus** [comment]
You could use [`del-cli`](https://github.com/sindresorhus/del-cli) which supports negation and uses `rimraf` underneath.

**Comment by stevenvanc** [comment]
> You could use del-cli which supports negation and uses rimraf underneath.
[del-cli](https://github.com/sindresorhus/del-cli) doesn't seem to support ** or *,

**Comment by sindresorhus** [comment]
@stevenvanc It does. Make sure you wrap the glob pattern in quotes.

**Comment by stevenvanc** [comment]
@sindresorhus Oh tnx. That wasn't really clear. Will look at it again later.

**Comment by mittalabhas1** [comment]
> You could use del-cli which supports negation and uses rimraf underneath.

Works like a charm. Thanks @sindresorhus

**Comment by pie6k** [comment]
Note that maybe using it like this `rimraf ./src/{folder1,folder2}/**/*.js` could help instead so instead of saying what you don't want to be removed, you're more strict about what you want to be removed.

**Comment by ffflorian** [comment]
You could also exclude files with a glob exclude pattern, e.g. `**/!(*.module).ts`.

**Comment by paschalidi** [comment]
what @ffflorian says works for me! Thx!

**Comment by szebert** [comment]
If you want to exclude node_modules when running rimraf in your node project, add this line to your package.json scripts: `"clean": "rimraf \"!(node_modules)/**/*.js\"",`
