### ISSUE TITLE
On windows, read-only directories are not removed, error with EPERM

### ISSUE THREAD

**Issue by iarna** [isaacs/rimraf#105]
This appears to be a regression due to b437e5e7a9140777ddd3631b995ebf0c8edec614, I'll have a PR for this shortly.

**Comment by iarna** [comment]
Specifically https://github.com/isaacs/rimraf/commit/b437e5e7a9140777ddd3631b995ebf0c8edec614#diff-d57672d4bbe9b41e3c1806e63407a07eR126 introduced a call to `rmdir` that's doesn't fallback to windows handling.

But that said, I've also found that you can set perms in windows such that `fs.stat` fails with EPERM too, which I find somewhat baffling. =D

**Comment by iarna** [comment]
All that said, it does appear to be trivially possible to chmod a dir to be unreadable and unremovable by any standard windows tool. =/

**Comment by gabrielsoltz** [comment]
Hi, i get this error while trying to remove some directories, 

C:\Users\Administrator\AppData\Roaming\npm\node_modules\rimraf\bin.js:37
      throw er
      ^

Error: EPERM: operation not permitted, rmdir 'Z:\BKP\xxx\xxx\xxx\xxx'
    at Error (native)
 C:\Users\Administrator\AppData\Roaming\npm\node_modules\rimraf\bin.js:37
      throw er
      ^

Error: EPERM: operation not permitted, rmdir 'Z:\BKP\xxx\xxx\xxx\xxx'
    at Error (native)

Maybe it is related ?

I tryed uncheck the read-only flag from the folder, but the issue continues.

Any idea ?

Thanks,

**Comment by Redmega** [comment]
I'm facing a similar issue. Tried to rimraf a folder, now I am locked out of it permanently. 

    C:\Users\path\to\\npm\node_modules\rimraf\bin.js:37
    throw er
      ^

    Error: EPERM: operation not permitted, unlink 'D:\workspaces\persproj\persproj'
        at Error (native)

**Comment by isaacs** [comment]
Can someone try doing `npm install isaacs/rimraf#gh-105` and see if that fixes the issue?

If @iarna's analysis is correct, then it should.  At least, I'd be surprised if it's harmful.

**Comment by Redmega** [comment]
I tried to find and delete the folder with 7-zip as I'd heard that can fix it. However the folder wasn't there to delete. So I killed and restarted explorer.exe and the folder was no longer there.

After that incident rimraf functioned as expected.

**Comment by nillis** [comment]
+1

**Comment by isaacs** [comment]
@nillis Are you +1-ing that the `gh-105` branch works for you?  Or are you just +1'ing that this is an issue for you?  https://github.com/isaacs/rimraf/issues/105#issuecomment-207715626

**Comment by nillis** [comment]
This was an issue for me, but I resolved the permission issue on the folder itself.

**Comment by luisotsm-pro** [comment]
just want to add that in my case was something with Atom tree folder view.
This error was always being throw if I had the tree folder expanded.
