### ISSUE TITLE
in windows 10 getting error of rimraf basedir=$(dirname $(echo $0 | sed -e s,\\,/,g))

### ISSUE THREAD

**Issue by born2net** [isaacs/rimraf#107]
in windows 10 getting error of:

```
> ng2-bs3-modal-born2net@0.2.13 clean C:\msweb\ng2-bs3-modal
> node ./node_modules/.bin/rimraf ./bundles/ ./components/ ./ng2-bs3-modal.js ./ng2-bs3-modal.d.ts

C:\msweb\ng2-bs3-modal\node_modules\.bin\rimraf:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

anyone seen this? workaround?

tx

Sean

**Comment by born2net** [comment]
nvm had to install globally ...

**Comment by isaacs** [comment]
@born2net That is the incorrect solution.

The `ng2-bs3-modal-born2net` module has a bug in its package.json.  It should not be doing `node node_modules/.bin/rimraf`.  It should just be doing `rimraf` only, without invoking node explicitly in this way.  This will never work on Windows.

**Comment by born2net** [comment]
yes I know, I fixed it on my end, for Windows has to be a direct call

**Comment by isaacs** [comment]
Pull request sent: https://github.com/dougludlow/ng2-bs3-modal/pull/47

**Comment by tessact** [comment]
```
"scripts": {
    "postinstall": "cross-env NODE_ENV=prod & node -max_old_space_size=8192 ./node_modules/.bin/gulp build:prod",
    "start": "node build/server-bundle.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
What should I do. This also gives the same error. When I removed ./node_modules/.bin/ and just kept gulp then it threw an error saying cannot find gulp file

**Comment by apurvgandhwani** [comment]
```
"scripts": {
    "postinstall": "cross-env NODE_ENV=prod & node -max_old_space_size=8192 ./node_modules/.bin/gulp build:prod",
    "start": "node build/server-bundle.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
What should I do. This also gives the same error. When I removed ./node_modules/.bin/ and just kept gulp then it threw an error saying cannot find gulp file
