### ISSUE TITLE
Multiple test failures in Windows

### ISSUE THREAD

**Issue by CurryKitten** [isaacs/rimraf#112]
I've found two problems when running the test suite on Windows machines.

Firstly, the sync and async removal in basic.js needs to run as administrator, else it'll fail with 

EPERM: operation not permitted, and then EEXIST failures subsequently as the file wasn't removed.  I don't think that having to run as administrator in Windows should be a necessary requirement - perhaps skip over these tests if the user doesn't have the requisite permissions ?

Secondly, in the custom-fs.js tests, there's no check for the windows file separator, so we see failures such as -

```
+++ found
--- wanted
 {
    "_keepDirs": { 
        ".": true 
        "a": true, 
-       "a/x": true 
-       "a/y": true 
-       "a/z": true
+       "a\x": true 
+       "a\y": true 
+       "a\z": true 
  }
```

**Comment by isaacs** [comment]
No longer applicable.
