### ISSUE TITLE
Feature: Support globbing negation/ignoring

### ISSUE THREAD

**Issue by requiemforameme** [isaacs/rimraf#113]
In reference to the npm [Glob module](https://www.npmjs.com/package/glob):

> **ignore** _Add a pattern or an array of glob patterns to exclude matches. Note: ignore patterns are always in dot:true mode, regardless of any other settings._

Ignore is a new option.

> **Comments and Negation**
> Previously, this module let you mark a pattern as a "comment" if it started with a # character, or a "negated" pattern if it started with a ! character.
> 
> These options were deprecated in version 5, and removed in version 6.
> 
> To specify things that should not match, use the ignore option.

It used to be that you could ignore certain patterns in globs with the exclamation mark:

    rimraf dist/!(bundle)*.js

That might not even be a valid glob, but you get the idea.  That would have deleted all JS files in the dist directory without "bundle" in their name.  

Was this functionality stripped from globbing, and thus impacted rimraf and tools like it?  Would it be possible to add a flag to ignore a pattern in a glob?

Or does this functionality already exist and I am completely missing something?

**Comment by isaacs** [comment]
Try this (on iPhone, so untested and perhaps has typos, please trust but verify)

```js
rimraf('dist/*.js', {
  glob: {
    ignore: 'dist/*bundle*.js'
  }
}, callback)
```

**Comment by sjelfull** [comment]
@isaacs Is this possible through the cli?

**Comment by isaacs** [comment]
@sjelfull No, the cli works just like `rm -rf`, by design.

Also, note that if a glob matches a folder, it's going to remove all the contents of that folder, even if something in the folder's contents is "ignored".  So, like `rimraf('foo', { glob: { ignore: 'foo/bar/baz' }})` will still remove `foo/bar/baz`, because `foo` was removed recursively.  The glob ignore only prevents the initial match.

You could do something like this, though:

```
$ mkdir -p foo/bar/{a,b,c,d,e}/{w,x,y,z} ; touch foo/bar/{a,b,c,d,e}/{w,x,y,z}/{1,2,3,4,5,6}.txt;
$ node -e 'require("rimraf").sync(process.argv[1], { glob: { ignore: process.argv[2] } })' 'foo/**/*.txt' 'foo/**/3.txt'
$ tree foo
foo
└── bar
    ├── a
    │   ├── w
    │   │   └── 3.txt
    │   ├── x
    │   │   └── 3.txt
    │   ├── y
    │   │   └── 3.txt
    │   └── z
    │       └── 3.txt
    ├── b
    │   ├── w
    │   │   └── 3.txt
    │   ├── x
    │   │   └── 3.txt
    │   ├── y
    │   │   └── 3.txt
    │   └── z
    │       └── 3.txt
    ├── c
    │   ├── w
    │   │   └── 3.txt
    │   ├── x
    │   │   └── 3.txt
    │   ├── y
    │   │   └── 3.txt
    │   └── z
    │       └── 3.txt
    ├── d
    │   ├── w
    │   │   └── 3.txt
    │   ├── x
    │   │   └── 3.txt
    │   ├── y
    │   │   └── 3.txt
    │   └── z
    │       └── 3.txt
    └── e
        ├── w
        │   └── 3.txt
        ├── x
        │   └── 3.txt
        ├── y
        │   └── 3.txt
        └── z
            └── 3.txt

26 directories, 20 files
```

**Comment by whitecolor** [comment]
I tried to exclude all nested node_modules folders but it doesn't work.
```
rimraf('dist/**', {
  glob: {
    ignore: `**/node_modules**`
  }
}, callback)
```

Seems strange.
