### ISSUE TITLE
rimraf fails if there is space in the path

### ISSUE THREAD

**Issue by vpezeshkian** [isaacs/rimraf#122]
I'm not able to use rimraf if there is SPACE in the path.

**Comment by isaacs** [comment]
Works for me.  Can you share any more details about how you're using rimraf?

**Comment by vpezeshkian** [comment]
Well the truth is I'm using `nwb` tool for my react app, there `rimraf`is used as module...
here take a look at this" https://github.com/insin/nwb/issues/181

Your module is used like this in `nwb` : ('rimraf', ['coverage', dist]);
The build is failing on Jenkins because I have spaces in my job name. 
I can confirm this because I renamed the job name without spaces and I was able to build and deploy. for some reason it takes the full path rather than relative...

**Comment by isaacs** [comment]
`rimraf` handles spaces fine.  Comment on original post.
