### ISSUE TITLE
EBUSY is not handled properly in SmartOS(Solaris) enviroment.

### ISSUE THREAD

**Issue by chayeon** [isaacs/rimraf#123]
Hi,

I'm using rimraf module in SmartOS(based on solraris) environment.
I tried to remove huge(?) amount of files with this module, but I got "EBUSY" error.

In rimraf function in rimraf.js, EBUSY is only handled on Windows in retrial maner.
`if (isWindows && (er.code === "EBUSY" || er.code === "ENOTEMPTY" || er.code === "EPERM") && 
               busyTries < options.maxBusyTries) { 
             busyTries ++`

Are there any issues if "isWindows &&" is removed?

Thank you.

**Comment by chayeon** [comment]
Hi,
FYI. I raised this issue to the project which is depending this module as follows;
(https://github.com/joyent/smartos-live/issues/673)
I think this issue is similar to the closed issue discussed in (https://github.com/isaacs/rimraf/issues/25).

Thank you.

**Comment by chayeon** [comment]
Hi,
I made a script to re-produce the issue in SmartOS as follows based on 'bin.js':


<b>ebusy_bin.js</b>
<pre>
<b>#!/usr/node/bin/node</b>

var rimraf = require('./')

var help = false
var dashdash = false
var args = process.argv.slice(2).filter(function(arg) {
  if (dashdash)
    return !!arg
  else if (arg === '--')
    dashdash = true
  else if (arg.match(/^(-+|\/)(h(elp)?|\?)$/))
    help = true
  else
    return !!arg
});

if (help || args.length === 0) {
  // If they didn't ask for help, then this is not a "success"
  var log = help ? console.log : console.error
  log('Usage: rimraf <path>')
  log('')
  log('  Deletes all files and folders at "path" recursively.')
  log('')
  log('Options:')
  log('')
  log('  -h, --help    Display this usage info')
  process.exit(help ? 0 : 1)
} else {
  args.forEach(function(arg) {
    <b>rimraf(arg, function(err){
      if (err)
        console.log("ERROR: " + err.code);
    });</b>
  })
}
</pre>

And bellow is test invocation method:
<pre>
tar xvfz git-2.8.0.tar.gz
./ebusy_bin.js ./git-2.8.0
</pre>
(To see EBUSY error you should run the above code repeatedly.)

The output is as follows when EBUSY error occurs:
<pre>
ERROR: EBUSY
</pre>

And the directory contents are left over as follows, but the contents are random:
<pre>
total 39458
-rwxr-xr-x 4 root root 9971208 Nov  2 03:54 git-init
-rwxr-xr-x 4 root root 9971208 Nov  2 03:54 git-ls-tree
-rwxr-xr-x 4 root root 9971208 Nov  2 03:54 git-mktag
-rwxr-xr-x 4 root root 9971208 Nov  2 03:54 git-name-rev
</pre>

FYI, the test env information is as follows:

node version: 0.10.26
test file: git-2.8.0.tar.gz
- download: https://www.kernel.org/pub/software/scm/git/git-2.8.0.tar.gz
- build: make (in linux)

Thank you.

**Comment by isaacs** [comment]
Handling EBUSY on other systems seems fine to me.  Would you like to submit a pull request?

**Comment by chayeon** [comment]
Yes, I'd like to.
Thank you.

**Comment by isaacs** [comment]
Fixed on 2.6
