### ISSUE TITLE
Disable globbing by default

### ISSUE THREAD

**Issue by binki** [isaacs/rimraf#127]
When I want globbing, I will specify it explicitly. Doing so requires you to think about the security consequences of turning on globbing. For example, you might have received a request to remove a directory with content in it called `/asdf/*/x` and verified that it exists and that deleting it would be OK and stored the result in a variable `path`, but executing `rimraf(path)` will cause `/asdf/y/x` to be deleted in addition to `/asdf/*/x`.

When I’m writing code and calling APIs that deal with paths, I expect path names to be actual path names—not to be expanded. So I find it very counterintuitive and unexpected that `rimraf()` expands globs by default when, e.g., [`fs.unlink()`](https://nodejs.org/api/fs.html#fs_fs_unlink_path_callback) won’t. And I would like to suggest that this could easily be dangerous. And, also, I don’t know for sure, but I assume that most people use rimraf just because [`fs.rmdir()`](https://nodejs.org/api/fs.html#fs_fs_rmdir_path_callback) (which doesn’t glob) doesn’t support recursion.

**Comment by NReilingh** [comment]
Possibly worth noting that when calling rm in a shell, it's the shell that parses the glob and then passes multiple individual paths to rm.

**Comment by binki** [comment]
@NReilingh [Not on Windows](https://stackoverflow.com/a/4094897/429091). In fact, I think the main reason that `rimraf` CLI has globbing behavior is to work around how Windows works. But that still makes it unsafe.

And because of the `rimraf` CLI’s glob expansion, if you properly escape a filename which contains embedded glob characters, suddenly `rimraf` CLI’s own globbing kicks in and does unexpected things:

```
ohnobinki@gibby ~ $ mkdir rimraf-play
ohnobinki@gibby ~ $ cd rimraf-play/
ohnobinki@gibby ~/rimraf-play $ npm init -y 2>&1 >/dev/null
ohnobinki@gibby ~/rimraf-play $ npm install --silent rimraf 2>&1 >/dev/null
ohnobinki@gibby ~/rimraf-play $ mkdir -p a/{b,\*\*}
ohnobinki@gibby ~/rimraf-play $ rm -rf a/\*\*
ohnobinki@gibby ~/rimraf-play $ rm -rf a/\*\*
ohnobinki@gibby ~/rimraf-play $ find a -print
a
a/b
ohnobinki@gibby ~/rimraf-play $ mkdir -p a/{b,\*\*}
ohnobinki@gibby ~/rimraf-play $ ./node_modules/.bin/rimraf a/\*\*
ohnobinki@gibby ~/rimraf-play $ ./node_modules/.bin/rimraf a/\*\*
ohnobinki@gibby ~/rimraf-play $ find a -print
find: ‘a’: No such file or directory
```

`rimraf` [has a hack to not do glob expansion if a file with the exact name exists](https://github.com/isaacs/rimraf/commit/4ddd0b2e5654b4c9454f21e020d7eff31bb2e2c2). But that only works to protect you when the file exists. Many people use `rimraf` where you would use `rm -rf`, and many people use that when they just want to assert that a certain path does not exist without first checking if it exists or not. So the hack to skip glob expansion upon exact match is insufficient to allow one to feel safe and comfortable when invoking `rimraf` non-interactively if you are passing a path which contains glob characters or a parameterized path (i.e., user/config-supplied or calculated at runtime).

**Comment by isaacs** [comment]
Globbing removed in v4.
