### ISSUE TITLE
rimraf CLI globbing is conditional and thus surprising

### ISSUE THREAD

**Issue by binki** [isaacs/rimraf#129]
When I pass the rimraf CLI a glob, it doesn’t expand the glob if an exact file with that name exists. But then next time I run the command it expands the glob. I always thought of `rm -rf` which `rimraf` is modeled after to be idempotent assuming no other process is interacting with the trees involved in the meantime. I.e., I wouldn’t expect running the same command twice with the same arguments to yield different results if I don’t touch the file tree in the meantime. See the transcript below.

```
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ mkdir -p a/{b{0,1,2,3},\*\*}/c
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ find . -name node_modules -prune -or -print
.
./a
./a/**
./a/**/c
./a/b3
./a/b3/c
./a/b2
./a/b2/c
./a/b1
./a/b1/c
./a/b0
./a/b0/c
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ nohup npm install rimraf@2.5.4 >/dev/null 2>&1
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ node_modules/.bin/rimraf 'a/**/c'
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ find . -name node_modules -prune -or -print
.
./a
./a/**
./a/b3
./a/b3/c
./a/b2
./a/b2/c
./a/b1
./a/b1/c
./a/b0
./a/b0/c
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ node_modules/.bin/rimraf 'a/**/c'
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $ find . -name node_modules -prune -or -print
.
./a
./a/**
./a/b3
./a/b2
./a/b1
./a/b0
ohnobinki@gibby /tmp/.private/ohnobinki/asdf $
```

**Comment by isaacs** [comment]
Hm.  I see the issue you're talking about.  This is tricky, though.

I'd be tempted to say that we just yank out globs from rimraf entirely.  After all, `rm -rf` doesn't expand globs, it just deletes exactly what it's given.

But `rm -rf` is typically executed from a shell that _does_ expand globs.  So, `rm -rf dir/*.txt` will remove all text files from `dir`.  Note that this is different from `rm -rf 'dir/*.txt'`, which will not expand the glob, and only delete the file actually named `dir/*.txt`.

The goal of the `rimraf` cli program is to emulate Unix `rm -rf` on windows, which does not have a `rm` command, or glob expansion in its shell.  So if someone replaces `rm -rf dir/*.txt` with `rimraf dir/*.txt` it should work as expected.

Except, on windows, this means that the rimraf command gets a single argument of `dir/*.txt` instead of a bunch of positional arguments `dir/a.txt dir/b.txt ...`.

Avoiding glob expansion for literal filename matches was to fix another issue, I'm not sure the history offhand.  Could probably dig through git blame and/or issues to find the story.

I'm not sure the best way to resolve this.  Maybe glob expansion in the rimraf cli should only happen on Windows?

**Comment by binki** [comment]
I think the least breaking way would be to switch back to the behavior of unconditionally expanding globs. It would  be nice if there was an argument to the CLI to opt out of the glob analogous to setting `opts={glob: false}`. I am betting that a `--no-glob` argument would be a more correct way of fixing the problem the literal match support was added for. I’m imagining:

    $ rimraf --no-glob "/path/with/wild*card/in/it/file.txt"
    $ rimraf "src/**/*~"
    $ rimraf -- -filename-starting-with-dash.txt
    $ rimraf --no-glob -- -filename-with-wild*card-starting-with-dash.txt

The `rimraf` CLI command’s support for globstar makes it more useful than normal shell globbing, and I’m sure people rely on that.

Regarding supporting Windows, for casual shell-mimicking glob expansion, I’m thinking that the most sensible/safe way of “fixing” this would be having a utility that does “normal” shell expansion to wrap invocations to `rimraf` in. I don’t know if something like this exists yet, and this is starting to get ridiculous. Also, I was thinking about recommending [`shx`](https://github.com/shelljs/shx), but their `rm` doesn’t support turning off globbing (https://github.com/shelljs/shelljs/issues/567). Anyway, what I have in mind would be to just wrap in something that acts like a normal shell that is provided either by rimraf or some other new package. This imaginary command would give you the same behavior on both Windows and unix if you always double-quote all of your arguments:

```
$ globexpand "node" "-e" "console.log(process.argv)" "*.txt"
[ '/usr/bin/node', 'a.txt', 'b.txt' ]
>globexpand "node" "-e" "console.log(process.argv)" "*.txt"
[ 'C:\\Program Files\\nodejs\\node.exe', 'a.txt', 'b.txt' ]
```

If this existed and you needed to disable rimraf’s globbing support for some reason and still needed shell-like behavior, then you would use that and make your `"scripts"` key much more complicated-looking. But for the normal case you would just escape your globs from the shell to explicitly use rimraf’s built-in globbing platform agnostically. E.g.:

    "scripts": {
      "shell-like-glob": "globexpand rimraf --no-glob -- \"*.txt\"",
      "rimraf-globbing": "rimraf \"**/*.txt\""
    }

That way you don’t accidentally use both POSIX shell *and* glob module’s globbing on unix and only the glob module’s globbing on Windows, ensuring more consistent cross platform behavior.

**Comment by binki** [comment]
4ddd0b2e5654b4c9454f21e020d7eff31bb2e2c2 appears to have introduced the check, Hmm… looks like adding glob support to rimraf broke some things and this was supposed to try to unbreak them instead of letting those package authors fix their scripts? Also, btw, for my own purposes (because I find globs scary), I already went and made a wrapper for `rimraf` called `rimraf-noglob` which behaves the way I’d expect rimraf to if it were to gain a --no-glob option: https://github.com/binki/rimraf-noglob#cli

**Comment by binki** [comment]
Ah, it appears that [`shx`](https://github.com/shelljs/shx) supports `--noglob` as a global-level setting and does the right thing when you use the sub-command `rm`. So the following are equivalent and fully cross-platform (except for the fact that you can’t include `*` in filenames on Windows, I should update my examples to use bracket expressions):

    $ shx --noglob rm -rf "a/[a-b]/c"
    $ rimraf-noglob "a/[a-b]/c"

**Comment by isaacs** [comment]
`--no-glob` added on 2.6.

**Comment by isaacs** [comment]
Globbing removed in v4.
