### ISSUE TITLE
[MacOS] ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by 45kb** [isaacs/rimraf#131]
Hi, first of all thanks a lot for this useful module.

I am facing `ENOTEMPTY` errors on MacOS .
As i can read from the readme i should `opts.maxBusyTries` if i am on Windows so i decided to gave it a try even if i am on Mac:

  ```rmRf(`${folder}/node_modules`, {'maxBusyTries': 3}, err => {
   console.log(err);
 });```

Unfortunately no luck...do you have any clue?
Is there something i am missing or doing wrong?

Thank you.

**Comment by Bazze** [comment]
+1

**Comment by shinnqy** [comment]
+1

**Comment by anupbaranwal** [comment]
I faced the same issue but on windows.

**Comment by brentonhouse** [comment]
@45kb - I am curious.  Why did you close this issue?  There are no comments as to why you did this and the issue is still outstanding.
