### ISSUE TITLE
rimraf mutates passed options

### ISSUE THREAD

**Issue by shinnn** [isaacs/rimraf#132]
```js
'use strict';

const rimraf = require('rimraf');
const opts = {};

opts; //=> of course, {}
rimraf.sync('foo', opts);
opts; /*=> {
  unlink: [Function],
  unlinkSync: [Function],
  chmod: [Function],
  chmodSync: [Function],
  stat: [Function],
  statSync: [Function],
  lstat: [Function],
  lstatSync: [Function],
  rmdir: [Function],
  rmdirSync: [Function],
  readdir: [Function],
  readdirSync: [Function],
  maxBusyTries: 3,
  emfileWait: 1000,
  disableGlob: false,
  glob: { nosort: true, silent: true }
} */
```

This causes some unexpected behavior if a user reuse the object elsewhere.

@isaacs Before submitting a pull request, I'd like to hear your opinion about whether this module should still support Node 0.x or not. If we can drop Node 0.x support, I'll fix this problem using native `Object.assign()`, otherwise I'll use some polyfill e.g. [`object-assign`](https://github.com/sindresorhus/object-assign) and [`xtend`](https://github.com/Raynos/xtend).

**Comment by isaacs** [comment]
No longer applicable in v4.
