### ISSUE TITLE
could u support a confirm prompt before del files?

### ISSUE THREAD

**Issue by Froguard** [isaacs/rimraf#134]
like a confirm dialog to remind users that it is a irreversibility opteartion

**Comment by tmarshall** [comment]
@Froguard confirm dialogs would need to built into a UI, which would not be part of this module.

**Comment by Froguard** [comment]
```
> Confirm delete target ? (yes/no)
> _
```

**Comment by tmarshall** [comment]
@Froguard sure, but this module is a utility. You can wrap it in a REPL module, but that should live outside of this repo

**Comment by isaacs** [comment]
Putting a dialog confirmation in this module is not really appropriate, and even checking for some kind of "onbeforedelete" callback would be prohibitively slow.  Sorry, not the place.
