### ISSUE TITLE
This need show status or show need permision.

### ISSUE THREAD

**Issue by SandHilt** [isaacs/rimraf#139]
I try remove some folders where Windows consider secure. Like Program Files.
But when i try delete with rimraf in these  locations, it just execute in loop.
I waited one hour and nothing.
If he can't delete, so he need a warning.
A status is good, like npm have.
Whatever, this plugin is good.

![Example of status from NPM](http://i1-news.softpedia-static.com/images/news2/npm-3-0-beta-is-out-adds-progress-bars-to-the-package-installation-screen-485474-3.jpg)

**Comment by isaacs** [comment]
Sounds like there is an error that is permanent and we're treating as temporary. What file are you trying to rimraf, on which version of windows?

Thanks for the report.

**Comment by SandHilt** [comment]
Like [Windows.old](https://www.howtogeek.com/223821/what-is-the-windows.old-folder-and-how-do-you-delete-it/) folders mess.
I can cleanup with cmd with superuser. But, rimraf no tell me about this.
It just try delete in a infinite loop and not show or send me a message.
