### ISSUE TITLE
Verbose Flag (for CLI)

### ISSUE THREAD

**Issue by mordentware** [isaacs/rimraf#140]
I was surprised to find that the verbose flag (`-v` or `--verbose`) was not supported, whereas it is within `rm`.

While this functionality could be considered as a separate package surrounding `rimraf`, the files being deleted are not exposed, meaning it would have to include its own globbing logic, handing single files to `rimraf` to delete and thereby losing much of the benefit of using it in the first place.

I appreciate the desire to keep any sort of UI out of `rimraf`, but given that `rm` supports `-v` (lines of `removed foo/bar/baz.txt`) and that `rimraf` advertises itself as a substitute for `rm -rf`, I figured it was worth a conversation.

**Comment by isaacs** [comment]
Sure.  Patch welcome :)

**Comment by xenoterracide** [comment]
I too would like this, seems like there was a PR long ago :'(
