### ISSUE TITLE
Why is rimraf slower than `rm -rf`?

### ISSUE THREAD

**Issue by SimplGy** [isaacs/rimraf#142]
I hope this doesn't come across as a complaint. I'm honestly trying to understand a root cause.

I have a nested folder structure that contains thousands of folders and files. It's part of a much larger build process I can't control.

It takes a full minute to clean this folder and I was trying to diagnose the issue. I noticed `npm`'s `del` uses `rimraf`, so I started using `rimraf` directly. It also takes a full minute to do the deletion. I've fiddled with the options a bit. I thought for speed it would make sense to turn off globbing and delete the whole parent directory:

    rimraf(buildDir + '/', {glob: false}); // full minute

This command takes a full minute as well. The platform specific command, however, is instantaneous:

    exec(`rm -rf ${buildDir}/*`) // instant

What accounts for this speed difference?

Would it be possible to make it faster in cases that involve parent directories that contain many files? Is this a difficult optimization to do across platforms?

**Comment by sindresorhus** [comment]
Can you try the synchronous method `rimraf.sync()` report back how it performs compared to the async one? What operating system and Node.js version are you on?

**Comment by SimplGy** [comment]
Can do. First maybe: how many files are we talking about?
`find ./build/ | wc -l` says more than 150k files. If I constrain to `-type l` I can see that all except 9k or so are are symlinks.

This is strange I think, but that part of the build system is not in my control.

What kind of timings do I see?

```
rimraf(ws.buildDir + '/', {glob: false}, done);         // 12s, 11s, 12s
rimraf(ws.buildDir + '/**', {}, done);                  // 29s, 32s, 32s
rimraf.sync(ws.buildDir + '/', {glob: false}); done();  // 18s, 18s, 20s
rimraf.sync(ws.buildDir + '/**', {}); done();           // 59s, 60s, 1.1m
```

I think I was using the sync versions in initial testing, but I cheated and removed it from the issue report to avoid a sync/async dogma debate. Turns out I shouldn't have because there's a performance diff.

I can't explain the difference between `glob: false` and not. I was very certain I tested both. Could be either that I measured poorly (called `done` at the wrong time) or there are variants in the build (this is a large system) that I didn't control for.

And my versions?

```
$ node -v // 4.2.6
osx 10.11.6
500gb SSD
```

**Comment by sindresorhus** [comment]
Seems like the main culprit here is [`glob`](https://github.com/isaacs/node-glob). I find it quite strange to have so many symlinks though.

The main reasons `rm -rf` is faster than `rimraf(ws.buildDir + '/', {glob: false}, done);` is that compiled native code is faster than JS and for every file the code has to cross the JS<->C++ bridge, which is very expensive, and you have a gadzillion files.

Can you also try with latest Node.js (7.8.0) and post the result here? Just to rule out it being a regression in Node.js 4.

**Comment by sindresorhus** [comment]
I wonder if the async version would be faster with some concurrency limit. I've had success with limiting the concurrency in the past to improve performance.

**Comment by sindresorhus** [comment]
Can you try out [this commit](https://github.com/sindresorhus/del/commit/66f069f1dedb7d077bc35b9d6c50f278418ff34c) of `del` where I've added a concurrency option?

```
$ npm i 'sindresorhus/del#66f069f1dedb7d077bc35b9d6c50f278418ff34c'
```

Try setting the option to different values and check if it improves the performance, like 5, 10, 20, 100. Make sure you test with latest Node.js as that's the version we should optimize for.

**Comment by jotto** [comment]
FYI, my own benchmark:

for an 8.1GB directory with 375,613 files:

MacOS El Capitan

* `rimraf.sync` 134s
* `rm -rf` 30s

**Comment by jotto** [comment]
with `del` 3.0.0 and concurrency of 100:

`rimraf.sync(dir, { glob: { concurrency: 100 } });`

64s (twice as fast as Infinity concurrency)

**Comment by isaacs** [comment]
`rimraf.sync` will always be considerably slower for complex trees, because it can only delete things sequentially, not in parallel.

But, regardless, v4 is much faster than it was now, and it's about as far as I can push it without writing an implementation in C, which seems sort of silly since `rm` already exists.  Use this if you want it to work cross platform or in Node programs.
