### ISSUE TITLE
Issue using npm 5.x

### ISSUE THREAD

**Issue by bjornharvold** [isaacs/rimraf#151]
npm 5.0.1
Node 7.10

13382 silly pacote trying rimraf@https://registry.npmjs.org/rimraf/-/rimraf-2.6.1.tgz by hash: sha1-wjOOxkPfeht/5cVPqG9XQopV8z0=
13383 verbose stack TypeError: Cannot read property 'find' of undefined
13383 verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:264:33)
13383 verbose stack     at Array.find (native)
13383 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:263:15)
13383 verbose stack     at emitNone (events.js:91:20)
13383 verbose stack     at Transform.emit (events.js:188:7)
13383 verbose stack     at endReadableNT (_stream_readable.js:975:12)
13383 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
13383 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by isaacs** [comment]
no longer applicable.
