### ISSUE TITLE
EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by c35xr** [isaacs/rimraf#156]
Hi, 

first thanks for your module bro, and i have a little issue with rimraf, I'm working on PC computer and I use the module only to delete the content on /dist folder, I'm using npm scripts to call rimraf 

```
"scripts": {
    "dev": "webpack-dev-server",
    "prod": "npm run clean && cross-env NODE_ENV=production webpack -p",
    "clean": "rimraf ./dist/*"
  }
```

the issue happens when try delete a recursive folder, in my case when try delete /images folder as this folder have others folders like /logo , /background , /icons , I move all images to /images folder and run npm run prod and works perfectly, so maybe is a little issue or maybe I'm implementing wrong rimraf.

the error log is this.

```
> sass-example@1.0.0 clean C:\Users\userName\Documents\sass
> rimraf ./dist/*

C:\Users\userName\Documents\sass\node_modules\rimraf\bin.js:47
      throw er
      ^

Error: EPERM: operation not permitted, unlink 'C:\Users\userName\Documents\sass\dist\images\background'
    at Error (native)
```

**Comment by PreciselyAlyss** [comment]
@c35xr Can you post the version of rifraf you are using?

**Comment by budarin** [comment]
I have the same bug on Windows

**Comment by zeljkomarinkovic** [comment]
Same bug on windows, have to restart vscode to get it working

**Comment by moyueating** [comment]
> Same bug on windows, have to restart vscode to get it working

thanks, it works for me, just restart vscode

**Comment by edsilv** [comment]
Restarting vscode worked for me too. Should we flag this with the vscode team?

**Comment by budarin** [comment]
every session I must restart vscode - it's a funny!?

**Comment by wendzhue** [comment]
@budarin Yes. I run into this problem about 3 months ago and then I switched to WebStorm. 🤣

**Comment by sarpik** [comment]
This issue still persists on Windows. Closing `vscode` solves it.

Any updates anyone?

**Comment by cornelg7** [comment]
I had a similar problem, solved it by stopping the live server I had open on the dist folder.
To stop VSCode's live server: `Ctrl + Shift + P` and type `>Live Server: Stop Live Server`

**Comment by isaacs** [comment]
EPERMs are handled appropriately now (or at least, it tries to handle them appropriately).
