### ISSUE TITLE
Miscellaneous Warning EINTEGRITY: sha1-(...) integrity checksum failed when using sha1:

### ISSUE THREAD

**Issue by StoneCypher** [isaacs/rimraf#157]
Hi.  It is not clear to me whether this reflects a problem with the package, or with my system.

```
John-Haugeland:jssm-viz-demo johnhaugeland$ npm install --save-dev rimraf
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= integrity checksum failed when using sha1: wanted sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= but got sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-wZyd+aAocC1nhhI4SmVSQExjbRU= integrity checksum failed when using sha1: wanted sha1-wZyd+aAocC1nhhI4SmVSQExjbRU= but got sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ==. (15621 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
```

On the one hand that looks like the server saying that, suggesting it isn't me.

On the other hand, nobody else seems to have this problem, and the current version is five months old. 

I am uncertain what to do.

**Comment by StoneCypher** [comment]
oh wait, it's asking for one kind of sha and receiving something else.

and this was right after i upgraded npm to 5.2.0

okay this isn't you, sorry.  nevermind.  leaving it open in case i'm wrong about being wrong

**Comment by StoneCypher** [comment]
yeah okay, this has gone away on its own for this package, and subsequently others

i think this is the result of a hot caching mechanism.  nevermind

**Comment by dosv01** [comment]
delete AppData/Roaming/npm and npm-cache and current package-lock.json,
then npm i -g npm, then npm install worked
(rajsite user solution)
