### ISSUE TITLE
[feature request] Add deleted files and directories in callback

### ISSUE THREAD

**Issue by lucas-viewup** [isaacs/rimraf#160]
Hi there! That would be useful had the feedback of **deleted files** and **directories**, here's the deal:

```javascript
rimraf( '**/.git', {glob: true}, function(err, files){
  
  if(err){
   throw new Error(err);
  }

  console.log( 'Deleted files:');

  files.map(function(file){
    console.log(file);
  });

});
```

A good reference is [glob](https://www.npmjs.com/package/glob).

Regards and thanks!

**Comment by zkochan** [comment]
I would love this feature as well. Or at least I would love to know when there was nothing to remove.

Seems like at the moment [del](https://github.com/sindresorhus/del) does this. And it uses rimraf under the hood

**Comment by isaacs** [comment]
Patch welcome.

**Comment by isaacs** [comment]
This will be possible in v4.3.0 by providing a `filter` option.  You can just return `true` in the filter to delete everything, and if you want to collect it up into an array or something, that's up to you.
