### ISSUE TITLE
Might be a good idea to add windows support

### ISSUE THREAD

**Issue by inunotaisho26** [isaacs/rimraf#168]
I have to know how to use Windows in case my job requires it, so I would like a rimraf windows version of this package made available. Otherwise I get this error:

`'rimraf' is not recognized as an internal or external command,
operable program or batch file.`

Screws with my projects I have written on Mac and Linux.

**Comment by etrupja** [comment]
@inunotaisho26 instead of 'rimraf' you can use the 'rm -rf' command.
