### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by spywhere** [isaacs/rimraf#169]
`rimraf@2.6.2` currently using `glob@4.0.6` which vulnerable to RegExp DoS as the details below. Please update the dependencies accordingly to resolve the issue.

<img width="501" alt="screen shot 2561-04-17 at 11 58 35" src="https://user-images.githubusercontent.com/1087399/38849533-b7b41b5c-4236-11e8-8acf-893bd0ef49a0.png">

**Comment by securit** [comment]
+1
