### ISSUE TITLE
Perform file check while deleting folder recursively with rimraf

### ISSUE THREAD

**Issue by vasyl-shumskyi** [isaacs/rimraf#170]
Hello,

How to perform file check while deleting folder recursively with rimraf?

For example, I need to delete all video files, but keep all other files. Pseudo-code: 

```javascript
rimraf(folder, err => { 
  if (err) console.error(err)
  else if (file-is-video) delete file
  // else do-not-delete file
})

**Comment by FireController1847** [comment]
You could use globs...

```js
rimraf **/*.mp4
```

Would delete all mp4 files. That's my limitation of how much I know about globs though lol

**Comment by isaacs** [comment]
Yeah, get the list of files you want to delete, and then pass it to rimraf, and it'll delete them and all their children.

Glob support removed in v4, but of course if you pass a glob on the cli, it'll be expanded just fine by the shell (if you're not on windows).
