### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by jacopolanzoni** [isaacs/rimraf#176]
--> DISCLAIMER: This problem may not be related to rimraf, but maybe you guys can point me into the right direction. <--

I have a NPM application built into a Maven project. I get the following error: 

```
[INFO] >activity-manager@1.2.0 clean-build C:\apps\activity-manager
[INFO] > rimraf app/{,**/}**.js app/{,**/}**.js.map app/{,**/}**.d.ts
[INFO]
[ERROR] The system cannot find the path specified.
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! activity-manager@1.2.0 clean: `npm run clean-build  && rimraf dist typings node_modules`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the activity-manager@1.2.0 clean script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The same command runs totally fine if I run it as 'node-modules/.bin/rimraf app/{,**/}**.js app/{,**/}**.js.map app/{,**/}**.d.ts'

I have also tried the following:
```
rimraf 'app/{,**/}**.js' 'app/{,**/}**.js.map' 'app/{,**/}**.d.ts'
rimraf \"app/{,**/}**.js\" \"app/{,**/}**.js.map\" \"app/{,**/}**.d.ts\"
```
but I had the very same result. 

I am at my wits end; any idea?

**Comment by isaacs** [comment]
It looks like your scripts aren't getting `node_modules/.bin` included as part of the PATH env.  Are you modifying that?
