### ISSUE TITLE
Deleting several elements with glob:false doesn't work?

### ISSUE THREAD

**Issue by warpdesign** [isaacs/rimraf#182]
With the rm command I'm used to remove several files/directories by typing `rm -rf foo bar`: this will delete the `foo` and `bar` elements.

Running this code with `rimraf` won't delete anything:

```
const rm = require('rimraf');

rm('foo bar', {
    glob: false
}, (err) => {
    if (err) {
        console.log('oops', err);
    } else {
        console.log('ok');
    }
});
```

Is there a way to delete several elements with using globs?

**Comment by isaacs** [comment]
v4 supports an array of paths, and glob support is removed.
