### ISSUE TITLE
rimraf shouldn't allow deleting /* by default

### ISSUE THREAD

**Issue by blubbll** [isaacs/rimraf#186]
breakign the project structure is bad, maybe add a "force" switch for that?
i messed up my project with this 3 times now.
glad i can go back.

**Comment by promethyttrium** [comment]
Or maybe you should test your commands better. Why is  this rimraf's fault?

**Comment by blubbll** [comment]
> Or maybe you should test your commands better. Why is this rimraf's fault?

Why should a lib be allowed to delete the processes base file without a warning? Especially in node.js where this is possible?

**Comment by isaacs** [comment]
`preserveRoot` option added some time ago.  `/` won't be traversed unless `preserveRoot: false` is set explicitly.
