### ISSUE TITLE
does not delete empty folder

### ISSUE THREAD

**Issue by rodoabad** [isaacs/rimraf#188]
While rimraf deletes the folder contents, it does not delete the folder itself.

```
    rimraf.sync(`${tempFolder}/**/*`, {
      glob: {
        dot: true
      }
    });
```

Expected: `tempFolder` also deleted
Actual: `tempFolder` still exist but empty

**Comment by nikolay-borzov** [comment]
Try this
```
rimraf.sync(tempFolder, {
  glob: {
   dot: true
  }
});
```

I guess using `${tempFolder}/**/*` like returns all files inside `tempFolder` excluding folder itself

**Comment by zkochan** [comment]
Maybe you need [fs-vacuum](https://github.com/npm/fs-vacuum)

**Comment by isaacs** [comment]
Glob support removed in v4.  Just give rimraf the path or array of paths you want deleted, and it'll do that.
