### ISSUE TITLE
Error when deleting .git folder in windows

### ISSUE THREAD

**Issue by satazor** [isaacs/rimraf#19]
This issue only happens in windows when using `rimraf 2.1.x`. When using `2.0.x` it works fine.
When `rimraf` is used to delete a git repository, it fails when removing `.git/objects/pack/*.idx and *.pack` files.

I've spotted this issue because I've upgraded rimraf in `0.8.x` release of http://github.com/twitter/bower and windows users started to complain. After some debugging, the `unlink` of these files error out with `EPERM`. Then `rimraf` interprets them as a directory and some other error happens. I think this is related to the fact the older versions of `rimraf` tried to make the file writable before deleting it.
When I tested, I had no hanging process on those files or the `.git` folder.

To reproduce:
`$ git clone git://github.com/satazor/SparkMD5.git`

``` js
var rimraf = require('rimraf');

rimraf('SparkMD5', function (err) {
  console.log(err);
});
```

**Comment by klarkc** [comment]
+1 This affects me, but in Linux.

Trying to remove test_sandbox folder:

Error: ENOTEMPTY, rmdir 'tests/test_sandbox/.git'

Looking for permission issues with this command: `$ find tests/test_sandbox/ -exec getfacl -t {} \; | grep "USER"`, give me this:

```
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rw-     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rw-     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rwx     
USER   klarkc    rw-
```

So none of the files have read only permissions nor are owned by someone else.
