### ISSUE TITLE
rimraf installs successfully but rimraf command not found on Windows

### ISSUE THREAD

**Issue by gbpatil** [isaacs/rimraf#193]
I've installed rimraf several times and on several machines. It installs the package successfully. When I'm using rimraf command, it errors out as "'rimraf' is not recognized as an internal or external command, operable program or batch file."
```
> npm install -g rimraf
C:\Users\UserName\AppData\Roaming\npm\rimraf -> C:\Users\UserName\AppData\Roaming\npm\node_modules\rimraf\bin.js
 \+ rimraf@2.6.3
updated 1 package in 1.695s

> rimraf
'rimraf' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by isaacs** [comment]
Seems like `node_modules/.bin` is not being added to the path, or the install just didn't work properly.
