### ISSUE TITLE
let glob in line 7

### ISSUE THREAD

**Issue by oskrvz** [isaacs/rimraf#194]
The use of 'let' is causing my project to fail because is not supporting it yet. Is is necesary to be?
How could I force my npm install to use the previous version (2.6.3)?
![imagen](https://user-images.githubusercontent.com/2512579/62993731-58d28a00-be1e-11e9-8ab9-92a7219d69ce.png)

**Comment by tomerzvirsh** [comment]
we encountered the same issue. waiting for #195.

**Comment by ljharb** [comment]
Similar comment [here](https://github.com/isaacs/rimraf/commit/dc1682d546114fd042f90e57af09da1959953395#r34690842); also broke many of my downstream tests.

**Comment by jeremy-dobler** [comment]
In my opinion, this is not a bug of rimraf. Rimraf correctly updated the major version when they released a change that broke backwards compatibility. This is valid and correct. Karma pulled in this new major version, via ^2.6.0, which ended up breaking builds for most users. Karma needs to fix their package.json so it doesnt pull in changes that break backwards compatible. Upgrades to the major version must be explicit changes, NOT automatic

**Comment by basavk** [comment]
Faced the same issue on our production systems.

To resolve the issue either upgrade your node version to 6.4.0 or downgrade rimraf to 2.6.3 in your package.json file

**Comment by johnjbarton** [comment]
The karma package.json is here: https://github.com/karma-runner/karma/blob/master/package.json#L409

Not it.

**Comment by isaacs** [comment]
https://github.com/isaacs/rimraf/commit/012ecbba814a74c3201ef63c54f6abcefa671be4
