### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by domoritz** [isaacs/rimraf#197]
Is there a changelog? It would be great to know what has changed with v3 so we can decide whether to update or not. Looking at the latest commits, it looks like you switched to using es6 (using `const` etc).

**Comment by isaacs** [comment]
That is correct.  Same logic, just drops support for very old node versions.

**Comment by Shinigami92** [comment]
_Luckily, I'm one of those people who can see if there's an identical issue that requests the same_

So... can we have a `CHANGELOG.md` or alternative [Release-Tags](https://github.com/isaacs/rimraf/releases) with information?

**Comment by isaacs** [comment]
https://github.com/isaacs/rimraf/commit/d82bc81f251ba2cc86dc26361a820631091b3e9e
