### ISSUE TITLE
Version 2.7.0 should not be compatible 2.2.8

### ISSUE THREAD

**Issue by balihoo-cnorwood** [isaacs/rimraf#198]
We have an old system that builds using node 4.  It uses `del` ver 1.2.1, which has in its dependencies
```"rimraf": "^2.2.8"```

Yesterday it built fine, today it broke because it pulled 2.7.0, which was released in the last 24 hrs.

**Comment by Favna** [comment]
Wouldn't it be more prudent to move towards ditching Node 4 and upgrading? I mean not saying that this issue is a non-issue, but Node 4 is waaay EOL. Currently Node 10 is LTS (8 being Maintenance LTS until December when it EOL's) and Node 6 went EOL earlier this year. [See Node releases here](https://github.com/nodejs/Release#readme)

**Comment by balihoo-cnorwood** [comment]
100% agree that it would be more prudent, I'm very familiar with node releases, and you can ignore the issue if you like, i'm sure very few are affected.

At this point you probably don't want to roll back your code changes that require node 6 or greater, perhaps next time follow `engines` guidelines from https://docs.npmjs.com/files/package.json#engines
> You can specify the version of node that your stuff works on:
> ```
> { "engines" : { "node" : ">=0.10.3 <0.12" } }
> ```
> And, like with dependencies, if you don’t specify the version (or if you specify “*” as the version), then any version of node will do.

**Comment by balihoo-cnorwood** [comment]
FYI - commit requiring node 6 was first part of 2.6.3, here's comment with more details.
https://github.com/isaacs/rimraf/commit/dc1682d546114fd042f90e57af09da1959953395#r34690842

**Comment by bcoe** [comment]
@isaacs any reason not to bump to 3.x and unpublish 2.7.x with a var instead of let?

Personally, while I think EOL versions of Node.js should be avoided, seems like this should be a major bump.

**Comment by bcoe** [comment]
I see this was already done, folks on Node 4 should switch to 2.7.1:

https://github.com/isaacs/rimraf/commit/012ecbba814a74c3201ef63c54f6abcefa671be4

**Comment by balihoo-cnorwood** [comment]
Thanks for the quick fix!!  I now see this a duplicate of #194
