### ISSUE TITLE
npm run rimraf from script not same result as cli run rimraf ... 

### ISSUE THREAD

**Issue by Luxcium** [isaacs/rimraf#202]
#### I have this in package.json scripts : 
**`"out:clean": "rimraf -rf ./build/**"`**

Using the script deletes the empty container but only the contents if not empty. Doing ` rimraf -rf ./build/**` from command-line interface deletes all the contents of `./build` but never the container ... 

Adding `'/'`at the end makes the behavior change only in the command line interface  ` rimraf -rf ./build/**/` will delete the container each time but `"out:clean": "rimraf -rf ./build/**/"` will have the same result and will delete the container only if empty or will only delete the contents...  

- **At the CLI without the trailing `'/'`** the command run twice in the CLI will delete the contents the first time and output a message the second time "`zsh: no matches found: ./build/**`"

- **At the CLI with the trailing `'/'`** the command run twice in the CLI will delete the container itself (and the contents) the first time and output a message the next time "`zsh: no matches found: ./build/**/`"

- **With `npm run 'script'` with or without the trailing `'/'`** the command run twice in the CLI using `npm run 'script'` will delete the contents the first time and delete the container the folowing time and will do nothing if run again (will not display message)...

**Comment by Luxcium** [comment]
Additional information : Darwin [...] Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin

**Comment by isaacs** [comment]
Welcome to weird shell glob behavior!

Your shell does not expand `**` to "all children and also the folder itself", it's just equivalent to `./build/*`.  So the arguments that the rimraf script get are equivalent to something like `rimraf ./build/a ./build/b ./build/c ...`

If you want the folder and all its children deleted, just do `rimraf ./build`.  It's recursive by default, there's no way to make it _not_ recursive.

Also, glob support removed in v4, so it'll just delete what you give it, no glob expansion.

**Comment by byronogis** [comment]
Just a hint (v6.0.1):

To avoid "no matches found" errors when using `*`, you can use quotes with glob (back in v4.2).

For example, if you want to deeply clean `node_modules` in your workspace/monorepo :

```
rimraf -g '**/node_modules'
```
