### ISSUE TITLE
unable to delete asar file

### ISSUE THREAD

**Issue by midnight1994** [isaacs/rimraf#203]
`rimraf('/path/app.asar', function (err) {
  if (err) {
    throw err
  }
  console.log('success')
})`
The prompt was successful, but the asar file was not deleted. How can I solve this problem?

**Comment by rajivkr** [comment]
I tried to run the same code.  rimraf was successfully able to delete asar file.
My code reference [here ](https://github.com/rajivkr/rimraf-test)
It is working fine. Probably you can try upgrading rimraf or re-installing it again.

**Comment by dancastellon** [comment]
A workaround I discovered. I renamed `app.asar` to `appasar` and ran rimraf against `appasar`. That worked.

**Comment by hgouveia** [comment]
by default electron will try to process .asar files, activating this flag `process.noAsar = true;` will be treating an asar archive as a normal file,

you can this only when using rimfar for example
```js
process.noAsar = true;
rimraf(somePath, (err) => {
   process.noAsar = false;
  //....
});
```
