### ISSUE TITLE
Add note that module is now shipped in node by default.

### ISSUE THREAD

**Issue by SimonSchick** [isaacs/rimraf#204]
See https://github.com/nodejs/node/pull/29168

**Comment by rajivkr** [comment]
Looks like documentation change. Can I take this up?

**Comment by mrmakeit** [comment]
One thing to note is that this isn't a direct ship, as the implementation is in fs.rmdir, and doesn't support a few things like glob.

**Comment by isaacs** [comment]
as of v4, this will use the node builtin where appropriate.
