### ISSUE TITLE
cwd option

### ISSUE THREAD

**Issue by dbkr** [isaacs/rimraf#210]
If you want to delete files in a different directory to `process.cwd()`, you need to `process.chdir()` before running `rimraf`. Glob has a `cwd` option to set the directory it works in, but if you set this option with `options.glob.cwd`, rimraf breaks because it's still looking in `process.cwd()` for the files to delete, so won't delete anything (or will delete some other random files if the same path appears in `process.cwd()`).

Rimraf could have a `cwd` option to support this, which it passed through to glob and then also prefixes to the results produced by glob (and maybe prevents the caller from directly setting glob's own `cwd` option).

Any interest in a PR for this?

**Comment by isaacs** [comment]
No thanks.  Glob dep removed.  Resolve the filenames before trying to delete them, or use a relative path to them from cwd.
