### ISSUE TITLE
Callback argument should be optional

### ISSUE THREAD

**Issue by SrBrahma** [isaacs/rimraf#214]
Quickly:

rimraf(path, () => { });

could just be

rimraf(path)

In some cases, your really don't care if you got errors.

Had this issue in Typescript. It doesn't allow not passing a callback.
In README.md, it says `rimraf(f, [opts], callback)`. Callback should be optional there as well.

**Comment by isaacs** [comment]
v4 uses promises.

**Comment by SrBrahma** [comment]
Many thanks!
