### ISSUE TITLE
Deletes unintended files when used with && operator

### ISSUE THREAD

**Issue by abir-taheer** [isaacs/rimraf#219]
My package.json looks like this:
```
"scripts": {
	"compile": "rimraf dist && npx babel src/ -d dist"
}
```
When I ran `npm run compile` babel gave me an error saying that my src/ directory doesn't exist and I found that rimraf had also deleted my src folder. This doesn't seem like the intended behavior.

**Comment by YellowAfterlife** [comment]
`&& ...` being passed to rimraf at all would mean that it's how it's being invoked. Not something on rimraf's end, unless you expect the tool to double as a shell processor. Perhaps [wrapping the command in a shell function or moving it to a separate shell file](https://stackoverflow.com/a/39997087/5578773) would help.

**Comment by isaacs** [comment]
Are you running this in Windows?  `&&` has a very different meaning to cmd than it does to sh.

Try this:

```json
{
  "scripts": {
    "precompile": "rimraf dist",
    "compile": "npx babel src/ -d dist"
  }
}
```
