### ISSUE TITLE
Error: glob dependency not found, set `options.disableGlob = true` if intentional

### ISSUE THREAD

**Issue by sunil-sandhu** [isaacs/rimraf#221]
Upon executing `this.browser.close()` to end a puppeteer process, the aforementioned error occurs every time. 

From what I can tell, `options` is defined as an empty object on line 51 of rimraf.js. Is it possible to add some logic into rimraf to check whether the `try/catch`block on line 5-9 of rimraf.js successfully requires glob?

One solution would be to add the following into the `rimraf` function on line 48:

```
  if(!glob) {
    options.disableGlob = true;
  } 
```

**Comment by Petr-Alexeev** [comment]
Faced with the same problem: `await browser.close()` failed with "`glob dependency not found, set options.disableGlob = true if intentional`".

Solved by adding glob to production dependencies.

**Comment by martinstark** [comment]
Suddenly running into this issue in multiple repos when running `rimraf dist/*` with yarn.

**Comment by Osiris-Team** [comment]
Facing the same issue and @martinstark idea with `npm install` doesn't work for me.
Any updates?

**Comment by martinstark** [comment]
I've not had time to investigate properly, but I've had less issues in mono-repo setups with yarn by staying on Node 12. YMMV.

**Comment by isaacs** [comment]
Glob dep removed in v4.
