### ISSUE TITLE
Node.js 14.14.0 adds fs.rm & fs.rmSync support

### ISSUE THREAD

**Issue by SukkaW** [isaacs/rimraf#224]
[`fs.rm`](https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_fs_rm_path_options_callback), [`fs.rmSync`](https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_fs_rmsync_path_options) and [`fsPromises.rm`](https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_fspromises_rm_path_options) API has been added since Node.js 14.14.0.

Any idea to utilize those Node.js FS API in `rimraf`? e.g, when no fancy options like `glob` provided while `fs.rm` is available, use Node.js built-in FS API directly for better performance.

**Comment by isaacs** [comment]
v4 uses these when available, and provides better fallbacks for the failures on Windows if you use `rimraf.manual()` explicitly.
