### ISSUE TITLE
version 4

### ISSUE THREAD

**Issue by isaacs** [isaacs/rimraf#228]
- [ ] remove glob dependency
- [ ] accept array of paths as well as a single path (so anyone who wants to glob can just do it themselves)
- [ ] Do not accept a callback.  Return a Promise.
- [ ] Use native `fs.promises.rm` and `fs.rmSync` in versions that support it
- [ ] Delete on Windows by renaming first https://youtu.be/uhRWMGBjlO8?t=457

**Comment by klh** [comment]
+1 for renaming first, in our team I consistently see macs outperform windows machine on DX builds by 10-20 seconds, solely because of the shitty rm -rf experience on windows.

Thoughts on the issue:
1: Not sure you would gain that much real life execution speed since you need to make sure that stuff IS deleted eventually - and for consistency you cannot return a true / resolved promise before that happens.
So the experience would probably be the same.

2: If you rename and move files wouldn't you run into issue with open files handle blocking the rename / move

**Comment by isaacs** [comment]
Explorations into the "rename first" option (including digging into some of the .NET and other "official" Microsoft source code that's available) turned out that it can take much longer (like 2x to 10x as long), and be just as inconsistent (because they can still be locked or busy, as you mention in (2).)

The way that official Microsoft tools do this is either to just do the naive POSIX approach, and use exponential backoff when errors happen, or use undocumented internal APIs to know exactly which syscall to use to remove something based on the state it's in (which Node.js doesn't provide, and probably never will).  In some cases, if the exponential backoff fails, tools just give up, or the function returns a successful result while the file still actually exists.  (Ie, the issue you mention in (1), they just do that, yolo.)

Your (3) suggestion (delete all non-dir files first, then all directories) is interesting, I'll look into that approach.

**Comment by klh** [comment]
Feeling the pain

**Comment by isaacs** [comment]
So it looks like what I could do which should have the best chance of success and decent enough performance is:

1. Naive posix-style recursive rm, but don't remove directories
2. Exponential backoff in the async case, retries in sync case, for ENFILE, EMFILE, and EBUSY.
3. Fall back to move-then-remove if that fails
4. Naive recursive rm for the remaining empty directories, falling back to move-then-remove for any ENOTEMPTY

**Comment by klh** [comment]
That sounds like a heap of complexity to add vs naive.
2 thoughts:
Introducing that logic tree may add several points of instability that may be hard to foresee (fat,ntfs,ext,netfs etc)

Would a worstcase scenario be so detrimental (perf wise) that it may ultimately fail? (Don't want that)

Maybe @madskristensen know this lowlevel stuff he's pretty cool with all things ms?

**Comment by isaacs** [comment]
The only thing that's really "complex" (above the current v3 rimraf, anyway, which is also still the the basis for Node's bundled fs.rm, afaik) is the move-then-remove strategy at the end if it hits ENOTEMPTY (which _should_ never happen, but does happen quite often when deleting large folder structures at maximum speed).

Benchmarks on the v4 PR (#229) show that it's faster than node's builtin for async removal, and about the same for sync, and I turned the benchmark settings up until I started hitting those EBUSY and ENOTEMPTY responses.  End of the day, this is all just explorations to hopefully improve what ships with node by default.  I don't think many people still use this module for new projects, since fs.rm works fine, and it won't really benefit older/unmaintained projects much if there's a major semver bump anyway.

**Comment by klh** [comment]
I've seen quite a lot of projects using this as a quick way to do various cross-system "cleanup" directly in npm scripts - but I agree fs.rm works pretty well as is.

**Comment by didaquis** [comment]
Do you have any idea when version 4 will be ready?

**Comment by isaacs** [comment]
It's merged into main, but I'd like to figure out how to get benchmarks running in an environment outside my own laptop. Might punt on that if it's just too annoying, since the speed and reliability does seem to be improved, I'd just like to know exactly how much. A naive GitHub action workflow running the bench script blew up because it ran out of space, so maybe I can just scale down how much stuff it's trying to delete.

**Comment by isaacs** [comment]
Another approach, of course, is just ship it and let people complain if it's slower or broken. Yolo-style oss integration testing lol. Which sounds irresponsible, but it is a semver major, so unlikely it'll burn anyone who doesn't opt in explicitly.

**Comment by isaacs** [comment]
Well, trimming down the benchmark CI weight did let it run successfully.  No slam dunks, but it's performing at or better than Node's built-in.  Margins are super narrow at this small of a benchmark dataset, but it's the only way I could get it to stop falling over.  I'm gonna ship it.
