### ISSUE TITLE
Different behavior of single command cross platform

### ISSUE THREAD

**Issue by shabbyk** [isaacs/rimraf#231]
This issue was observed with a specific command.

`rimraf ./build/static ./build/*.*`

Windows: This command removes _static folder_ and all other _files_ from build folder. Every thing else remains.
Linux: This command removes everything from build folder.

Observation: This command is in post-build section of my react app. It works perfectly on local machine (windows). But when I push the code, the pipeline(Linux) executes the same command but the output is different as explained above.

I may be wrong. If this is a know issue please let me know.

Cheers!

**Comment by mjohenneken** [comment]
Have you tried `rimraf ./build/static/ ./build/*.*` ?

**Comment by isaacs** [comment]
Works for me.

```
$ tree build
build/
├── do/
│   └── not/
│       └── delete/
│           └── me/
├── static/
│   ├── a.foo
│   ├── b.foo
│   ├── c.foo
│   └── d.foo
├── a.txt
├── b.txt
├── c.txt
└── d.txt

5 directories, 8 files

$ rimraf build/static build/*.*

$ tree build
build/
└── do/
    └── not/
        └── delete/
            └── me/

4 directories, 0 files
```

**Comment by isaacs** [comment]
Works with more files and folders there, too, nothing getting touched except what should be

```
$ tree build/
build//
├── do/
│   ├── not/
│   │   └── delete/
│   │       └── me/
│   ├── a.txt
│   ├── b.txt
│   ├── c.txt
│   └── d.txt
├── nodelete/
│   ├── me/
│   │   └── please/
│   ├── a.txt
│   ├── b.txt
│   ├── c.txt
│   └── d.txt
├── static/
│   ├── a.foo
│   ├── b.foo
│   ├── c.foo
│   └── d.foo
├── a.txt
├── b.txt
├── c.txt
├── d.txt
└── nodothere

8 directories, 17 files

$ rimraf build/static build/*.*

$ tree build/
build//
├── do/
│   ├── not/
│   │   └── delete/
│   │       └── me/
│   ├── a.txt
│   ├── b.txt
│   ├── c.txt
│   └── d.txt
├── nodelete/
│   ├── me/
│   │   └── please/
│   ├── a.txt
│   ├── b.txt
│   ├── c.txt
│   └── d.txt
└── nodothere

7 directories, 9 files
```
