### ISSUE TITLE
Yarn audit High : minimatch 

### ISSUE THREAD

**Issue by ellisium** [isaacs/rimraf#242]
Please update glob dependency version

**Comment by didaquis** [comment]
Related info:   https://github.com/advisories/GHSA-f8q6-p94x-37v3


<img width="649" alt="Captura de pantalla 2023-01-12 a las 14 07 38" src="https://user-images.githubusercontent.com/6883041/212074348-fbc4cc6f-fe8c-431e-8ae3-bd69423e2e9f.png">

**Comment by isaacs** [comment]
Removed in v4.
