### ISSUE TITLE
after install rimraf, i received error msg "rimraf not found"

### ISSUE THREAD

**Issue by edusurf10** [isaacs/rimraf#246]
![image](https://user-images.githubusercontent.com/26351660/212108742-dca8cfba-1d9a-4439-841f-e71b32c45613.png)

![image](https://user-images.githubusercontent.com/26351660/212108600-f381e882-5fd2-4f5f-99a1-d182f0e712c8.png)

**Comment by isaacs** [comment]
Is there a binary being created at `node_modules/.bin/rimraf`?  Do other npm scripts work?

This doesn't seem like a rimraf error, it seems like an npm error, tbh.
