### ISSUE TITLE
Fuzzy matching can't be used

### ISSUE THREAD

**Issue by code-ManL** [isaacs/rimraf#260]
on window:
`  
 "scripts": {

    "clean": "rimraf packages/*/dist"
  }
`

![image](https://user-images.githubusercontent.com/91084928/222874574-c3162f26-7de6-45a9-b98b-d9d3f6a133df.png)

**Comment by dpilafian** [comment]
I believe it's **glob** not **regex** that you're trying to use.  Judging from the updated readme, it looks like the new usage needs the `--glob` flag and the path to be quoted.

Something like this might work:
```json
"scripts": {
   "clean": "rimraf --glob 'packages/*/dist'"
},
```
