### ISSUE TITLE
Dependency bloat

### ISSUE THREAD

**Issue by jirutka** [isaacs/rimraf#274]
It adds 25 dependencies to a project using Babel, TypeScript and ESLint. This is completely insane for a simple utility doing just `rm -rf` with globbing.

https://bundlephobia.com/package/rimraf@5.0.1:
![image](https://github.com/isaacs/rimraf/assets/949228/4293d505-fd27-4fdf-8fcd-4e4eebb88443)

https://npmgraph.js.org/?q=rimraf:
![image](https://github.com/isaacs/rimraf/assets/949228/c7c372fa-d4a4-4975-a213-61f5009e5c91)

**Comment by isaacs** [comment]
Thanks for sharing your feelings.

Why are you bundling rimraf for web browsers? 25kb is not even a rounding error server-side.

**Comment by jirutka** [comment]
> Why are you bundling rimraf for web browsers?

I’m not, this is just for illustration.

> 25kb is not even a rounding error server-side.

Size is not what I see as the problem here, the number of dependencies is.

**Comment by isaacs** [comment]
Ok, so are you suggesting that this lib should not have a cli, should not support globs, or that all those things should be inline instead of shared deps in node_modules?

**Comment by isaacs** [comment]
> Size is not what I see as the problem here, the number of dependencies is.

You're using babel, typescript, and eslint and you're worried about my 25 deps? Lol

Just use fs.rm if that bothers you.
