### ISSUE TITLE
Symlink's real files is deleted in Windows

### ISSUE THREAD

**Issue by jamkitGO** [isaacs/rimraf#276]
**What happen：**
I found many people will use this lib to delete the files `node_modules` , so am I, it's helpful. But I found that in Windows, it will delete the symlink (usually created by `npm link`) in `node_modules`. And What it actually do is deleted the real file (symlink's real file) too. 

Maybe it's our fault to use `rimraf` in that way, but it's dangerous (my symlink's real repository is deleted, which is unpushed 😢 ).

**Expected：**
Maybe give some warning?

**Comment by isaacs** [comment]
Weird. Does lstat say it's a directory rather than a symbolic link? Maybe should return to the "try unlink, rmdir on EISDIR"? That fails on sunos though, where it's sometimes possible to unlink a directory and then bad stuff happens.
