### ISSUE TITLE
Circular dependency warnings with Rollup

### ISSUE THREAD

**Issue by brc-dd** [isaacs/rimraf#279]
Hi, when trying to bundle rimraf using Rollup or similar tools, there are warnings like these:

```
(!) Circular dependency
node_modules/.pnpm/rimraf@5.0.1/node_modules/rimraf/dist/mjs/index.js -> node_modules/.pnpm/rimraf@5.0.1/node_modules/rimraf/dist/mjs/opt-arg.js -> node_modules/.pnpm/rimraf@5.0.1/node_modules/rimraf/dist/mjs/index.js
```

This happens because of these imports (opt-arg imports things from index and index imports opt-args):

https://github.com/isaacs/rimraf/blob/bfda548deddff84ca2b7ced40675b1b2648ee9bb/src/opt-arg.ts#L2-L7

Haven't got any issue with this so far, but I wonder if it would be better to move the common stuff to other file?

**Comment by AngeloCore** [comment]
Bump
