### ISSUE TITLE
Is Node 14 supported?

### ISSUE THREAD

**Issue by SimenB** [isaacs/rimraf#281]
`glob@9` dropped support for it, but it's still tested in this project.

https://github.com/isaacs/rimraf/blob/bfda548deddff84ca2b7ced40675b1b2648ee9bb/package.json#L82
https://github.com/isaacs/rimraf/blob/bfda548deddff84ca2b7ced40675b1b2648ee9bb/.github/workflows/ci.yml#L9

**Comment by isaacs** [comment]
I wouldn't say it's "supported", but yes, empirically it does work for now. If you wanna use EOL platform versions like node 14, you're kind of on your own. Be very careful about every dep update, pin dependency versions, maybe even check node_modules into git, that sort of thing.
