### ISSUE TITLE
Missing types for glob dependency

### ISSUE THREAD

**Issue by paulsmithkc** [isaacs/rimraf#286]
Using `rimraf@5.0.1` I am getting the following typescript error:

```
node_modules/rimraf/dist/mjs/index.d.ts:2:29 - error TS7016: Could not find a declaration file for module 'glob'. '---/node_modules/glob/glob.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/glob` if it exists or add a new declaration (.d.ts) file containing `declare module 'glob';`

2 import { GlobOptions } from 'glob';
                              ~~~~~~

Found 1 error in node_modules/rimraf/dist/mjs/index.d.ts:2
```

**Comment by paulsmithkc** [comment]
Workaround, pin the glob version:
```
npm install glob@10.3.6
```

**Comment by isaacs** [comment]
Actual fix for this: enable [resolvePackageJsonExports](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports).

Glob just stopped exporting incorrect types for its commonjs build. You have to tell typescript that your node version supports `exports` and so it should, too. I recommend `"module": "node16"` or `"module": "nodeNext"` in your tsconfig.

A similar change will be made in rimraf shortly.
