### ISSUE TITLE
Module `minimatch/dist/mjs/index.js` not found

### ISSUE THREAD

**Issue by siguici** [isaacs/rimraf#301]
node:internal/modules/esm/resolve:265
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path-to-my-project/node_modules/rimraf/node_modules/glob/node_modules/minimatch/dist/mjs/index.js' imported from /path-to-my-project/node_modules/rimraf/node_modules/glob/dist/esm/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///labs/path-to-my-project/node_modules/rimraf/node_modules/glob/node_modules/minimatch/dist/mjs/index.js'
}

**Comment by jonkoops** [comment]
If you want to have your issue resolved I recommend that you provide reproducible steps for the problem, otherwise it will just be closed.

**Comment by siguici** [comment]
Sorry for the late reply and for the lack of details. You can reproduce the bug as follows:

1- Clone the repository at `https://github.com/siguici/reflex.js`
2- Install dependencies with `bun install`
3- Then execute the `bun run build` command

The error is at this level. This command is supposed to clean up previous builds using `rimraf` before building again.

**Comment by siguici** [comment]
> The error message indicates that the version of minimatch/glob being provided to rimraf are not the versions that it declares as dependencies.
> 
> I can't help you. If your package manager gives my code the wrong deps, instead of the versions that rimraf states it's compatible with, then it won't be compatible and it won't work.
> 
> Looks like a bun issue, if that's the package manager you used to install this broken setup. But it works for everyone else. Not a rimraf bug.

Indeed, the issue seems to be related to Bun. I've encountered similar errors with other packages in different projects. I've used `rimraf` in other projects without encountering any issues.

Thank you for your understanding and sorry for the inconvenience.

**Comment by jonkoops** [comment]
@siguici perhaps try deleting all the `node_modules` and `bun.lockb` and re-install the packages, that has fixed stuff for me before.

**Comment by isaacs** [comment]
Everyone: please stop reporting and discussing package manager errors in the issues of the libraries affected by them. We can't fix them for you. Take it to bun, or yarn, or npm, or whatever you're using. "I got the wrong version of a dep" is almost *never* the fault of the dep itself, but whatever is loading it and choosing the wrong version.

I get a ton of isues like this, and I will be immediately closing and locking all of them moving forward.
