### ISSUE TITLE
Continue after ENOENT: no such file or directory

### ISSUE THREAD

**Issue by basickarl** [isaacs/rimraf#305]
I get this error when a directory doesn't exist that I am trying to remove. Would be good with a flag so that the command can skip this and go to the next file/directory in the list.

`ENOENT: no such file or directory`

**Comment by isaacs** [comment]
How are you getting rimraf to raise an `ENOENT`? That shouldn't be possible, when it encounters an `ENOENT` it just returns successfully. Can you share some code to reproduce it?

**Comment by isaacs** [comment]
Probably you need to update your rimraf dep. what does `npm ls rimraf` output?
