### ISSUE TITLE
Node 18 is not a dead version

### ISSUE THREAD

**Issue by Mister-Hope** [isaacs/rimraf#313]
See https://nodejs.org/en/about/previous-releases, node 18 is a valid LTS version till June 2025, so **unless there are strong reasons that you must drop it**, you'd better support it.

---

Edited: I already checked every upstream package bumps, none of them seems not working on node18.

You'd better create a patch on all these packages to add node 18 back

**Comment by isaacs** [comment]
It's dead to me.
