### ISSUE TITLE
Please re-add node 18 as valid engine

### ISSUE THREAD

**Issue by JamesHenry** [isaacs/rimraf#316]
Opened issue to improve visibility of comment here: 

https://github.com/isaacs/rimraf/commit/9b2a2b13e79516794fc910aa7ca3e37563c777cf#r144765941

Node 18 is not dead for quite a while yet (not until 2025-04-30), and many (most?) OSS projects support node versions while the node team does.

**Comment by isaacs** [comment]
It's dead to me. Keep using the old major as long as you like, I have no plans (or ability) to remove it from the npm registry.

Between v18 and v20, node _dramatically_ changed the way that loaders and importers work, and the only way to provide test coverage for ESM typescript, in a reasonable way, is to use custom import loaders. Thus, running tests for both versions in CI and dev is just prohibitively difficult, and I do not care to be bothered with it in my personal time, nor am I willing to claim support for something that isn't tested well enough to reliably stay good. Hence, the hard break.
