### ISSUE TITLE
I can't make it work on Windows 8.1

### ISSUE THREAD

**Issue by borisschapira** [isaacs/rimraf#60]
Hi,

I've installed rimraf as a dependancy for one of my projects, following the advices of http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/. But I can't make it work. Nothing happens. I've tried to install it globaly with no more success.

Any hint as to what could have gone wrong ?

**Comment by danielweck** [comment]
Duplicate: https://github.com/isaacs/rimraf/issues/62
