### ISSUE TITLE
using rimraf in an npm build script setup with issues on Windows 8.1

### ISSUE THREAD

**Issue by sonicpunk** [isaacs/rimraf#62]
We have the following script call in our npm scripts list
"scripts": {
 "clean": "rimraf assets/tpl/dist/*"
 }

Unfortunately Windows does not understand the /* on our command line.  It would be great if glob was built in as a dependency and integrated - https://www.npmjs.com/package/glob

**Comment by danielweck** [comment]
Duplicate: https://github.com/isaacs/rimraf/issues/60
(using `glob` sounds like a good idea)

**Comment by danielweck** [comment]
Here's how I fixed this problem:

in `package.json`:

```
...
"devDependencies": {
...
	"glob": "latest",
...
  },
  "scripts": {
    "clean1": "rimraf dist/*",
    "clean2": "node rimraf.js dist/*",
    "prebuild": "npm run clean2",
...
  }
```

New file `rimraf.js`:

```
var glob = require("glob")
var rimraf = require("rimraf");

var args = process.argv.slice(2);

console.log("Clean.js arguments: ");
console.log(args);

glob(args[0], {}, function (er, files) {
	if (er) console.log(er);
	for (var i in files) {
		console.log(files[i]);
		rimraf(files[i], function(e) {
			if (e) console.log(e);
		});
	}
})
```

**Comment by danielweck** [comment]
By the way, I applied the same technique to `jshint`:

in `package.json`:

```
...
"devDependencies": {
...
	"glob": "latest",
...
  },
  "scripts": {
    "lint1": "jshint assets/scripts/**.js",
    "lint2": "node jshint_glob.js assets/scripts/**.js",

    "prebuild": "npm run lint2 && npm run clean2",
...
  }
```

New file `jshint_glob.js`:

```
var glob = require("glob")
var jshint = require("jshint");
var fs = require('fs');

var args = process.argv.slice(2);

console.log("jshint.js arguments: ");
console.log(args);

var lint = function(files, i, ok) {
	if (i >= files.length) {
		if (!ok) {
			process.exit(2);
		}
		return;
	}
	
	var file = files[i];

	fs.readFile(file, function(err, fileContents) {
		
		if(err) {
			console.log(err);
			lint(files, ++i, ok);
			return;
		}
		
		var okay = jshint.JSHINT(fileContents.toString());
		if (!okay) {
			ok = false;
			console.log("!!! " + file);
			
			var out = jshint.JSHINT.data();
			var errors = out.errors;

			for(var j = 0; j < errors.length; j++) {
				console.log(errors[j].line + ':' + errors[j].character + ' ' + errors[j].reason + ' (' + errors[j].evidence + ')');
			}
		} else {
			console.log("... " + file);
		}
		
		lint(files, ++i, ok);
	});
};

glob(args[0], {}, function (er, files) {
	if (er) console.log(er);
	
	lint(files, 0, true);
});
```

**Comment by mendenhallmagic** [comment]
Another solution at the moment be to use [rimraf-glob](https://www.npmjs.com/package/rimraf-glob), which composes this module with glob, which is what @danielweck is doing by hand.
I would love to see this feature implemented here, but I could also see why it doesn't belong, strictly speaking. When typing `rm -rf *.whatever` into bash, it's bash that performs the file expansion (globbing?), not `rm`.

**Comment by danielweck** [comment]
When using my Glob wrapper script (see comment further above) to delete all files inside the "dist" folder of my application, I noticed that the `dist/**` glob expands to a list of files that includes the "dist" folder itself (on Windows, I have not tried on OSX yet). So I'm using `dist/*` instead, which works just fine as `rimraf` deletes subfolders appropriately.

**Comment by pratyushtewari** [comment]
I added `npm run clean` with the other commands to get this working.
```
  "scripts": {
    "clean": "rimraf <folder location to delete inside your project>",
    "build": "npm run clean && skpm-build",
    "watch": "skpm-build --watch",
    "start": "skpm-build --watch --run"
  },
```
