### ISSUE TITLE
differing behavior between api and cli

### ISSUE THREAD

**Issue by olsonpm** [isaacs/rimraf#63]
given the following dir
```
foo
  /bar.txt
  /baz.txt
```
running cli command "rimraf foo/\*" removes all the files while keeping the fonts directory intact.  However running the api command "rimraf('foo/\*', cb)" results in the files not being removed.

**Comment by isaacs** [comment]
This lib does not expand globs. Try this (typed on iOS, not tested)

```javascript
glob('foo/*', function(er,files){
  if(er) cb(er)
  else async.forEach(files, rimraf, cb)
})
```

Using http://npm.im/glob and http://npm.im/async

**Comment by olsonpm** [comment]
That will work just fine.  Thanks for your suggestion.
