### ISSUE TITLE
it appears the latest release is causing ember-cli users grief

### ISSUE THREAD

**Issue by raytiley** [isaacs/rimraf#65]
related issue: https://github.com/ember-cli/ember-cli/issues/3413

adding `"rimraf": "2.2.8"` to the top level `package.json` (forcing all the descendent deps to downgrade) seems to resolve the issue.

cc @stefanpenner

**Comment by raytiley** [comment]
I've confirmed the issue is related to isaacs/node-glob#170, however i'm not sure if that fix will fix ember-cli right away. 

One of the broccoli plugins is calling rimraf with a broken symlink. rimraf does not remove the broken symlink. We aren't calling rimraf with any options so fixing the bug itself won't fix our problem.

@isaacs do you think the issue with node-glob will be fixed soon? If so I can submit a PRs to plugins using rimraf to pass the `nonull` option.

**Comment by raytiley** [comment]
Just realized that `rimraf` is calling `node-glob` and that we can't pass those options in to rimraf. Sorry for the noise.

**Comment by isaacs** [comment]
@raytiley I will fix the glob problem soon (this afternoon or this evening, us/pacific time) and publish a new rimraf version with the bugfix.

In the meantime, I've tagged rimraf 2.3 as "latest" in npm, so you *should* theoretically get that version by default in fresh installs.  Please let me know if that isn't the case.  Thanks!

**Comment by raytiley** [comment]
@isaacs Thanks. It has indeed been fixing new installs after clearing npm cache. Thanks for looking into this so quickly.

**Comment by stefanpenner** [comment]
> @raytiley I will fix the glob problem soon (this afternoon or this evening, us/pacific time) and publish a new rimraf version with the bugfix.

thanks @isaacs for the quick response :)
