### ISSUE TITLE
'glob' has no method 'hasMagic' error in v2.3.2

### ISSUE THREAD

**Issue by sweatypitts** [isaacs/rimraf#67]
Woke up to a broken build and tracked it down to v2.3.2, probably 4ddd0b2. I have not submitted a PR because I don't have time at the moment, but will start if I'm not beaten to it. Probably can't until later today or tomorrow.

rimraf is used by broccoli-caching-writer, which is used by ember-cli, which is why I was affected by this by the way. Anybody who did not peg their rimraf version < 2.3.2 and is using ember-cli is probably experiencing this too.

```
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at Function.rimrafSync [as sync] (/.../node_modules/rimraf/rimraf.js:262:13)
    ...
```

**Comment by alexBaizeau** [comment]
Same here.

**Comment by sweatypitts** [comment]
Hey @alexBaizeau! I met you at EmberConf! We ate lunch together the second day!

**Comment by alexBaizeau** [comment]
Haha that's funny, I did not notice the sweaty pits though :smile:

**Comment by isaacs** [comment]
What version of glob is it pulling in?  `hasMagic` was added in 4.2.0, and rimraf requires glob `^4.4.2`.

```
* eaab0ee isaacs add glob.hasMagic function (4 months ago)
```

I would really like it if we could get to a world where ember-cli stopped shipping the wrong deps for things.  I don't even know how this is happening, if it's a bug in ember-cli or in npm, but it's causing a lot of problems.

**Comment by isaacs** [comment]
That is, if you run `npm ls` and get a bunch of errors, then that's the problem.  This is not a rimraf bug.  It's an ember-cli and/or npm bug.

**Comment by backspace** [comment]
npm WARN unmet dependency node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
    npm WARN unmet dependency node_modules/ember-cli/node_modules/glob,
    npm WARN unmet dependency which is version 4.0.5

Indeed!

**Comment by backspace** [comment]
This has been discussed in an [Ember CLI issue](https://github.com/ember-cli/ember-cli/issues/3486).

**Comment by Heft9nic** [comment]
npm rm glob && npm up
npm i glob

**Comment by Heft9nic** [comment]
npm rm glob && npm up
npm i glob

**Comment by kemoycampbell** [comment]
another easy fix is to remove both nodejs and npm then reinstall. This way you get the most updated version of both nodejs and npm.
