### ISSUE TITLE
error building ember addon

### ISSUE THREAD

**Issue by deefactorial** [isaacs/rimraf#69]
steps to reproduce:
-git clone https://github.com/indexiatech/ember-idx-tree.git
-npm install
-bower install
-ember server
```javascript
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
```
    at Function.rimrafSync [as sync] (/home/deefactorial/git/ember-idx-tree/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:262:13)

looks like a es6-shim issue in the rimraf node module

**Comment by deefactorial** [comment]
rimraf requires glob ^4.4.2

**Comment by isaacs** [comment]
Duplicate #67
