### ISSUE TITLE
rimraf doesn't work

### ISSUE THREAD

**Issue by Webbrother** [isaacs/rimraf#71]
I installed "rimraf" from npm and tested it, but it just does nothing. Nothing heppens after rimraf command. What am I doing wrong?

OS Win7x64
node -v  v0.12.0
npm -v   2.5.1
```
Z:\test_folder>

Z:\test_folder>rimraf Z:\test_folder

Z:\test_folder>rimraf "Z:\test_folder"

Z:\test_folder>rimraf "Z:\test_folder\"

Z:\test_folder>rimraf Z:\test_folder\

Z:\test_folder>

**Comment by marclundgren** [comment]
hmm. It worked for me. Did you install globally?

**Comment by isaacs** [comment]
Maybe Windows is failing to delete the folder you're currently in?

**Comment by quetzalcoatl** [comment]
I'm absolutely sure it is not possible. The `cmd` process simply holds a handle to current directory.

    Microsoft Windows [Wersja 6.1.7601]
    Copyright (c) 2009 Microsoft Corporation. Wszelkie prawa zastrzeżone.

    C:\Users\quetzalcoatl>mkdir foo

    C:\Users\quetzalcoatl>cd foo

    C:\Users\quetzalcoatl\foo>rmdir ..\foo
    Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces.

    C:\Users\quetzalcoatl\foo>

The error message above roughly translates to

    Process cannot access the file because it is being used by another process.

**Comment by isaacs** [comment]
Yeah, tested this.  `cmd.exe` will lock the current working directory.  If you `cd z:\` and then run your command, it works fine.

**Comment by Webbrother** [comment]
still doesn'w work

**Comment by Webbrother** [comment]
Still doesn't work. Very strange.
I tried to use it on D: partition with test folder it works fine. Then I tested it on C: partition and didn't work. I tried to change dir (go up) and it didn't help.
I have no idea what's the reason.
