### ISSUE TITLE
rimraf fails in combination with gulp.src

### ISSUE THREAD

**Issue by sondreb** [isaacs/rimraf#78]
This fails on Windows 10 (not sure about other versions):

```javascript
gulp.task("rimraf", function () {

    return gulp.src('./wwwroot/modules/settings/**/*.js', { read: false })
            .pipe(rimraf());

});
```

Error output:
**AssertionError: "undefined" == true
    at Object.rimraf (C:\Source\Repos\...\node_modules\rimraf\rimraf.js:41:3)**

I tried to clone the repo and debug what was going on, and the input to the rimraf method are all undefined (p, options, cb).

I do think the code above is in accordance with the documentation here: https://www.npmjs.com/package/gulp-rimraf

I did notice that the package is deprecated, so I'm changing to use "del" package in node, though just wanted to let you know of the issue.

**Comment by isaacs** [comment]
rimraf() is not a stream.  You can't pipe to it.

`rimraf(globOrFileName, function (er) { if (!er) { it worked }})`

When you call `rimraf()` like that with no arguments, that's like doing `rimraf(undefined, undefined, undefined)` so yes, that is what's happening.

In the code sample you're using, they're doing `var rimraf = require('gulp-rimraf')`, so it's not this function.

**Comment by sondreb** [comment]
Thanks! I see the examples on the gulp-rimraf package is easy to misunderstand, as the first example uses rimraf directly and not gulp-rimraf. Thanks for clarifying!

**Comment by isaacs** [comment]
Oh, one other thing: `gulp-rimraf` may be deprecated but *this* module, `rimraf`, is actively maintained and widely used.
