### ISSUE TITLE
cant create  phonegap app, always get rm: could not remove directory (code ENOTEMPTY):

### ISSUE THREAD

**Issue by Le8080** [isaacs/rimraf#84]
I always get  rm: could not remove directory (code ENOTEMPTY): ... when i do phonegap create command.
please see screen shot below

![image](https://cloud.githubusercontent.com/assets/13539860/8998862/41a5bb8e-3765-11e5-9cba-89218546c9d8.png)

![image](https://cloud.githubusercontent.com/assets/13539860/8998867/46958b2e-3765-11e5-8baf-b1d6b2c10576.png)

**Comment by yuricamara** [comment]
Same problem here!

**Comment by yoshuawuyts** [comment]
@yuricamara can you specify more details? What version are you running, what npm and node do you have installed, what OS are you on? Sharing a repro also increases the chance people will look at it and try and help you out. Cheers!

**Comment by yuricamara** [comment]
It seems that the problem happens when PHPStorm is opened. I don´t think it is rimraf guilt. But I keep you informed.

NPM 2.11.2
Node 0.12.4
Windows 10

**Comment by isaacs** [comment]
Same as #85

**Comment by siempay** [comment]
same here 
`$ cordova platform remove android`
`rm: could not remove directory (code ENOTEMPTY): C:\shop\cordova\mobileapp\platforms\android/assets`

`rm: could not remove directory (code ENOTEMPTY): C:\shop\cordova\mobileapp\platforms\android/assets`
`rm: could not remove directory (code ENOTEMPTY): C:\shop\cordova\mobileapp\platforms\android`

**Comment by cikcoh** [comment]
same here

**Comment by MitchellBouwman** [comment]
> It seems that the problem happens when PHPStorm is opened. I don´t think it is rimraf guilt. But I keep you informed.

For me it was my VScode which was open..

**Comment by isaacs** [comment]
Try on v4. It's a bit more persistent on Windows.
