### ISSUE TITLE
cant create  phonegap app, always get rm: could not remove directory (code ENOTEMPTY):

### ISSUE THREAD

**Issue by Le8080** [isaacs/rimraf#85]
I always get  rm: could not remove directory (code ENOTEMPTY): ... when i do phonegap create command.
please see screen shot below

![image](https://cloud.githubusercontent.com/assets/13539860/8998862/41a5bb8e-3765-11e5-9cba-89218546c9d8.png)

![image](https://cloud.githubusercontent.com/assets/13539860/8998913/aacd7c0a-3765-11e5-85f4-907d668460b4.png)

**Comment by isaacs** [comment]
Can you please retry with the latest version of rimraf?  I believe some recent changes have likely fixed this.
