### ISSUE TITLE
Wait/retry loop guards against EBUSY but not against EPERM

### ISSUE THREAD

**Issue by quetzalcoatl** [isaacs/rimraf#86]
I was studying https://github.com/meteor/meteor/issues/4933 and I noticed that RIMRAF contains a smart delay loop that guards against momentary EBUSY or ENOTEMPTY conditions. It might be beneficial to add to that the EPERM condition. Windows seem to rise EPERM when file handles to files from the folder being deleted are still not fully released.

**Comment by isaacs** [comment]
It does now.

```
          if (isWindows && (er.code === "EBUSY" || er.code === "ENOTEMPTY" || er.code === "EPERM") &&
```
