### ISSUE TITLE
gulp task example

### ISSUE THREAD

**Issue by antonk52** [isaacs/rimraf#92]
Please add a code example how to use this module in build process using gulp.

**Comment by yoshuawuyts** [comment]
@antonk52 you sound like you're demanding an example of `rimraf` + `gulp`. Though you probably mean well, to me your tone comes over as very unpleasant. The maintainers of this package have better things to do than create an example of `rimraf + X`. Instead I can encourage you to experiment on your own with whatever packages you're mashing together, and ask around on IRC (Freenode - #node, #nodeschool) / Twitter or the issues on what you're doing wrong.

If you're new to JS / Node in general, consider doing a few [nodeschool](http://nodeschool.io) tutorials to get yourself acquainted with the Node ecosystem. Cheers! :sparkles:

**Comment by antonk52** [comment]
Hi. Did not mean to sound demanding at all. I opened the issue as most of npm packages have multiple examples of how they are used in the projects. I have been experimenting with this as well as other packages which lead to a similar result. As I came across this one I noticed that it's documentation can be improved and made a suggestion. Maybe that did sound a bit off from what I intended it to sound like. 

I know and still thrilled how willing to help strangers can be in the web community. 

Thank you for your comment.

**Comment by yoshuawuyts** [comment]
Is this helpful?
```js
const rimraf = require('rimraf')
const path = require('path')

rimraf(path.join(__dirname, './my-directory'), function (err) {
  if (err) throw err
})
```
I wrote [an article](https://medium.com/@yoshuawuyts/mastering-the-filesystem-in-node-js-4706b7cb0801#.d9z9nimcd) about using fs packages in Node, perhaps that's useful too?

**Comment by antonk52** [comment]
Thank you for the code. I did get it to work. Before that, guess my issue was due to node's asynchronicity. Still thank you sir. Appreciate the effort
