### ISSUE TITLE
Store all errors

### ISSUE THREAD

**Issue by piranna** [isaacs/rimraf#94]
Reading the code seems only first error is stored, although other files keep being removed and so others could lead to errors too. Since we are already using a global variable to store the error, use it instead as a mapping path->error and return it instead.

**Comment by isaacs** [comment]
I'm ok with this as a configurable option.  The default (fail on first error, only return the first error encountered) should be preserved as the default, though.

**Comment by isaacs** [comment]
Patch (with docs and test) welcome :)

**Comment by isaacs** [comment]
v4 implementation is different.  No longer applicable.
