### ISSUE TITLE
Is async really better than sync?

### ISSUE THREAD

**Issue by mikeobrien** [isaacs/rimraf#95]
Sorry, bit of a rant. I am getting so tired of this dogma being mindlessly repeated by every javascript developer on the planet (Just look at SO when someone asks about a sync version of something):

> It can remove stuff synchronously, too. But that's not so good. Use the async API. It's better.

It's like saying "here is a hammer, it's not so good, use a screwdriver, it's better". And then when I need to drive nails I have this javascript dev saying "don't use a hammer for that, use a screwdriver! Screwdriver good! Hammer bad!" (Or "not so good", same thing). I really think leaders in the javascript community need to instead help people to reason on when to use different approaches instead of repeating "async is better, sync is bad" mantra ad nauseum. It's just not a true statement and it undermines the credibility of the javascript community. Hammers and screwdrivers can be both good or bad depending on what you are trying to accomplish. Why not explain that the sync version is really bad for node servers but may be a great fit for things like scripting? </rant>

Anyways, sorry for the rant. Nothing personal, more of a general frustration.

**Comment by yoshuawuyts** [comment]
> Why not explain that the sync version is really bad for node servers but may be a great fit for things like scripting

If you feel documentation can be improved, PRs are always welcome.

That said: firing off a rant in an issue is honestly not the best way to get your message across; you come off sounding badly, and you contribute to the stress levels of the developers on the other side. 

Remember that this is a community of people with feelings, that often maintain these things in their spare time. Being respectful of people and their time is a good way to start.

**Comment by mikeobrien** [comment]
@yoshuawuyts definitely not my intention to cause any distress, offend or disrespect.

**Comment by isaacs** [comment]
Primary author/maintainer here.  Sync stuff is fine, that's why this module has it.  Doc patch welcome.  No offense was caused, it's all good.

**Comment by mikeobrien** [comment]
@isaacs sorry for the late night rant, was coding in anger, literally. Will try to work something up and submit a PR.

**Comment by isaacs** [comment]
Code angry, debug calm. It's a pretty good system :)

**Comment by mikeobrien** [comment]
Sage advice. :)
