### ISSUE TITLE
API Clarification

### ISSUE THREAD

**Issue by dakanji** [isaacs/rimraf#96]
Can you please clarify in the ReadMe how the **"unlink, chmod, stat, lstat, rmdir, readdir unlinkSync, chmodSync, statSync, lstatSync, rmdirSync, readdirSync”** options should be passed to the API?

Would that be something like ...

``` javascript
rimraf(f, {rmdir: true}, callback)
```

**Comment by datnordstrom** [comment]
+1

**Comment by FBRTMaka** [comment]
+1

**Comment by isaacs** [comment]
You pass in functions that are used instead of the default `fs` methods.

```javascript
rimraf(f, { rmdir: myCustomDirRemovalFunction }, callback)
```

**Comment by pixelass** [comment]
+1. 
This project really deserves a better readme/API description.  
Right now the lack is keeping me from using it because I do't want to have to pick around in the source code to understand how it works.

**Comment by isaacs** [comment]
@pixelass Doc patch welcome.  It's really pretty simple, though.  `rimraf(someFileOrFolder, callbackFunctionToCallWhenItsDone)`.  The function you pass in gets called when the recursive removal has completed.  The sync version is the same, but no callback `rimraf.sync(someFileOrFolder)`.

The options object is only for edge cases you probably don't need to ever worry about.  If you do, they're documented pretty explicitly.

**Comment by pixelass** [comment]
@isaacs I'll see what I can do. I can add some basic documentation but will most likely need help on the validity.

**Comment by isaacs** [comment]
@pixelass I'm happy to review any doc PR you send over.  It's easier to tell you what's wrong than write it myself :)

**Comment by jantimon** [comment]
@pixelass impressive docs 👍
