### ISSUE TITLE
Add option to set glob dot option to true

### ISSUE THREAD

**Issue by laverboy** [isaacs/rimraf#97]
When trying to empty a directory one can use the glob pattern `adirectory/*`. However this does not remove dot files.

Please allow an option to apply the `dot:true` setting to the glob modules. See https://github.com/isaacs/node-glob#dots

Thanks

**Comment by isaacs** [comment]
```javascript
rimraf('adirectory/*', {
  glob: {
    dot: true
  }
}, callbackFunction)
```

Or just `rimraf('adirectory', function () { fs.mkdir(adirectory, cb) })` to remove it entirely and then re-create it.

**Comment by laverboy** [comment]
Must have missed that. Thanks
