### ISSUE TITLE
rimraf removes files not owned by the user

### ISSUE THREAD

**Issue by radare** [isaacs/rimraf#98]
Default behaviour in the unix `rm` is not to remove files that are not owned by the user or doesn't have permissions for it by default. rimraf removes them without reporting this which can be dangerous or maybe undesired in some situations.

This is the test case, which i wrote for the `rmdir` npm module:

https://github.com/dreamerslab/node.rmdir/issues/11

But using this index.js:
```js
require('rimraf')('foo', console.log);
```

**Comment by yoshuawuyts** [comment]
`rimraf` is like unix `rm -rf`; does appending the `-f` flag also report errors?

Only have a single user on all my machines; would've tested it directly otherwise.

**Comment by isaacs** [comment]
If you don't have permission to remove the dir, then it'll error.

If you don't *own* it, but you *do* have permission to remove it, then it will just silently remove it, like `rm -rf`.  That's what the `f` says.

This is 100% working exactly as designed.

```
$ mkdir -p foo/bar/baz

$ sudo chown nobody foo

$ node -p 'require("rimraf").sync("foo")'
/Users/isaacs/dev/js/rimraf/rimraf.js:304
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'foo'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:763:18)
    at rmkidsSync (/Users/isaacs/dev/js/rimraf/rimraf.js:334:11)
    at rmdirSync (/Users/isaacs/dev/js/rimraf/rimraf.js:324:7)
    at Function.rimrafSync [as sync] (/Users/isaacs/dev/js/rimraf/rimraf.js:295:9)
    at [eval]:1:19
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:566:27

$ sudo node -p 'require("rimraf").sync("foo")'
undefined

$ ls -laF foo
ls: foo: No such file or directory
```
